FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV UV_COMPILE_BYTECODE=1
ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONPATH=/app/src

RUN apt-get update &&\
   apt-get install -y curl

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock ./

COPY src/ ./src
COPY docs/ ./docs
COPY data/vdb ./data/vdb
COPY .env ./.env

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked
