# -*- coding: utf-8 -*-
"""Definition_embeddings.ipynb

Automatically generated by Colab.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -vI milvus-model transformers==4.44.2

from milvus_model.hybrid import BGEM3EmbeddingFunction
import polars as pl
import pickle

dense_ef = BGEM3EmbeddingFunction(use_fp16=False, return_sparse=False)
sparse_ef = BGEM3EmbeddingFunction(use_fp16=False, return_dense=False)
hybrid_ef = BGEM3EmbeddingFunction(use_fp16=False)

processed_df = pl.read_csv("definitions.csv")

def_list = processed_df["definition_text"].to_list()

definendum_list = (processed_df.select(
    pl.col('label')
    .str.replace('#', '')
    .str.replace(r'([a-zà-ÿ])([A-Z])', r'${1} ${2}', n=-1)  # Add space between lowercase and uppercase letters
    .str.to_lowercase()  # Convert to lowercase after splitting
)
)['label'].to_list()

defs_embeddings_dense = dense_ef(def_list)

defs_embeddings_sparse = sparse_ef(def_list)

definendums_embeddings = sparse_ef(definendum_list)

defs_embeddings = hybrid_ef(def_list)

defs_embeddings.keys()

with open("defs_embeddings_dense.pkl", "wb") as f:
    pickle.dump(defs_embeddings_dense, f)

with open("defs_embeddings_sparse.pkl", "wb") as f:
    pickle.dump(defs_embeddings_sparse, f)

with open("defs_embeddings.pkl", "wb") as f:
    pickle.dump(defs_embeddings, f)

with open("definendums_embeddings.pkl", "wb") as f:
    pickle.dump(definendums_embeddings, f)